import { createSlice, type PayloadAction } from "@reduxjs/toolkit";

/* Instruments */
import { incrementAsync } from "./thunks";

const initialState: ProductSliceState = {
  value: 0,
  status: "idle",
  data: [],
};

export const productSlice = createSlice({
  name: "product",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setProduct: (state) => {
      state.value;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(incrementAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(incrementAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.value += action.payload;
      });
  },
});

/* Types */

export interface ProductSliceState {
  value: number;
  status: "idle" | "loading" | "failed";
}
